
var Sf167Web = (() => {
  var _scriptName = import.meta.url;
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

function aa(){k.buffer!=l.buffer&&n();return l}function r(){k.buffer!=l.buffer&&n();return ba}function t(){k.buffer!=l.buffer&&n();return ca}function v(){k.buffer!=l.buffer&&n();return da}function ea(){k.buffer!=l.buffer&&n();return fa}var w=Object.assign({},moduleArg),ha,x,ia=new Promise((a,b)=>{ha=a;x=b}),ja="object"==typeof window,z="function"==typeof importScripts,ka="object"==typeof process&&"object"==typeof process.ma&&"string"==typeof process.ma.node,A=z&&"em-pthread"==self.name;
w.listen||(w.listen=a=>console.log(a));w.onError||(w.onError=a=>console.error(a));w.getRecommendedNnue=(a=0)=>C(la(a));w.setNnueBuffer=function(a,b=0){if(!a)throw Error("buf is null");if(0>=a.byteLength)throw Error(`${a.byteLength} bytes?`);const c=ma(a.byteLength);if(!c)throw Error(`could not allocate ${a.byteLength} bytes`);w.HEAPU8.set(a,c);na(c,a.byteLength,b)};w.uci=function(a){const b=oa(a)+1,c=ma(b);if(!c)throw Error(`Could not allocate ${b} bytes`);pa(a,c,b);qa(c)};w.print=a=>w.listen?.(a);
w.printErr=a=>w.onError?.(a);var ra=Object.assign({},w),sa=[],D="",ta;if(ja||z)z?D=self.location.href:"undefined"!=typeof document&&document.currentScript&&(D=document.currentScript.src),_scriptName&&(D=_scriptName),D.startsWith("blob:")?D="":D=D.substr(0,D.replace(/[?#].*/,"").lastIndexOf("/")+1),z&&(ta=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ua=w.print||console.log.bind(console),E=w.printErr||console.error.bind(console);
Object.assign(w,ra);ra=null;
if(A){var va,wa=!1;function a(...c){console.error(c.join(" "))}w.printErr||(E=a);self.alert=function(...c){postMessage({ea:"alert",text:c.join(" "),qa:F()})};w.instantiateWasm=(c,e)=>new Promise(g=>{va=f=>{f=new WebAssembly.Instance(f,xa());e(f);g()}});self.onunhandledrejection=c=>{throw c.reason||c;};function b(c){try{var e=c.data,g=e.cmd;if("load"===g){let f=[];self.onmessage=h=>f.push(h);self.startWorker=()=>{postMessage({cmd:"loaded"});for(let h of f)b(h);self.onmessage=b};for(const h of e.handlers)if(!w[h]||
w[h].proxy)w[h]=(...q)=>{postMessage({ea:"callHandler",pa:h,oa:q})},"print"==h&&(ua=w[h]),"printErr"==h&&(E=w[h]);k=e.wasmMemory;n();va(e.wasmModule)}else if("run"===g){ya(e.pthread_ptr,0,0,1,0,0);za(e.pthread_ptr);Aa();Ba();wa||=!0;try{Ca(e.start_routine,e.arg)}catch(f){if("unwind"!=f)throw f;}}else"cancel"===g?F()&&G(-1):"setimmediate"!==e.target&&("checkMailbox"===g?wa&&H():g&&(E(`worker: received unknown command ${g}`),E(e)))}catch(f){throw Da(),f;}}self.onmessage=b}
var k,Ea,J=!1,K,l,ba,ca,da,fa;function n(){var a=k.buffer;l=new Int8Array(a);new Int16Array(a);w.HEAPU8=ba=new Uint8Array(a);new Uint16Array(a);ca=new Int32Array(a);da=new Uint32Array(a);new Float32Array(a);fa=new Float64Array(a)}
if(!A){if(w.wasmMemory)k=w.wasmMemory;else if(k=new WebAssembly.Memory({initial:1024,maximum:32768,shared:!0}),!(k.buffer instanceof SharedArrayBuffer))throw E("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),ka&&E("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),Error("bad memory");
n()}var Fa=[],Ga=[],Ha=[],Ia=[],Ja=[],Ka=!1,L=0,La=null,M=null;function Ma(){L--;if(0==L&&(null!==La&&(clearInterval(La),La=null),M)){var a=M;M=null;a()}}function Na(a){a="Aborted("+a+")";E(a);J=!0;K=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");x(a);throw a;}var Oa=a=>a.startsWith("data:application/octet-stream;base64,"),Pa;function Qa(a){if(ta)return ta(a);throw"both async and sync fetching of the wasm failed";}
function Ra(a){return(ja||z)&&"function"==typeof fetch?fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>Qa(a)):Promise.resolve().then(()=>Qa(a))}function Sa(a,b,c){return Ra(a).then(e=>WebAssembly.instantiate(e,b)).then(c,e=>{E(`failed to asynchronously prepare wasm: ${e}`);Na(e)})}
function Ta(a,b){var c=Pa;return"function"!=typeof WebAssembly.instantiateStreaming||Oa(c)||"function"!=typeof fetch?Sa(c,a,b):fetch(c,{credentials:"same-origin"}).then(e=>WebAssembly.instantiateStreaming(e,a).then(b,function(g){E(`wasm streaming compile failed: ${g}`);E("falling back to ArrayBuffer instantiation");return Sa(c,a,b)}))}function xa(){Ua={y:Va,f:Wa,t:Xa,u:Ya,m:Za,z:$a,k:ab,x:bb,i:cb,g:db,j:za,h:eb,d:fb,l:gb,b:hb,w:ib,r:jb,p:kb,q:lb,c:N,e:mb,s:nb,n:ob,v:pb,a:k,o:qb};return{a:Ua}}
function rb(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var sb=a=>{a.terminate();a.onmessage=()=>{}},vb=a=>{0==O.length&&(tb(),ub(O[0]));var b=O.pop();if(!b)return 6;P.push(b);Q[a.Y]=b;b.Y=a.Y;b.postMessage({cmd:"run",start_routine:a.ga,arg:a.fa,pthread_ptr:a.Y},a.la);return 0},R=0,jb=()=>0<R,T=(a,b,...c)=>{for(var e=c.length,g=wb(),f=S(8*e),h=f>>3,q=0;q<c.length;q++){var B=c[q];ea()[h+q]=B}a=xb(a,0,e,f,b);yb(g);return a};
function zb(a){if(A)return T(0,1,a);K=a;0<R||(Ab(),J=!0);throw new rb(a);}var Eb=a=>{if(!(a instanceof rb||"unwind"==a))throw a;};function Fb(a){if(A)return T(1,0,a);--R;N(a)}var N=a=>{K=a;if(A)throw Fb(a),"unwind";0<R||A||(Gb(),U(Ia),Hb(0),Ib[1].length&&Jb(1,10),Ib[2].length&&Jb(2,10),Ab(),Ka=!0);zb(a)},O=[],P=[],Kb=[],Q={};function Lb(){for(var a=navigator.hardwareConcurrency;a--;)tb();Fa.unshift(()=>{L++;Mb(()=>Ma())})}
var Ab=()=>{for(var a of P)sb(a);for(a of O)sb(a);O=[];P=[];Q=[]},Ob=a=>{var b=a.Y;delete Q[b];O.push(a);P.splice(P.indexOf(a),1);a.Y=0;Nb(b)};function Ba(){Kb.forEach(a=>a())}
var ub=a=>new Promise(b=>{a.onmessage=f=>{f=f.data;var h=f.cmd;if(f.targetThread&&f.targetThread!=F()){var q=Q[f.targetThread];q?q.postMessage(f,f.transferList):E(`Internal error! Worker sent a message "${h}" to target pthread ${f.targetThread}, but that thread no longer exists!`)}else if("checkMailbox"===h)H();else if("spawnThread"===h)vb(f);else if("cleanupThread"===h)Ob(Q[f.thread]);else if("killThread"===h)f=f.thread,h=Q[f],delete Q[f],sb(h),Nb(f),P.splice(P.indexOf(h),1),h.Y=0;else if("cancelThread"===
h)Q[f.thread].postMessage({cmd:"cancel"});else if("loaded"===h)a.loaded=!0,b(a);else if("alert"===h)alert(`Thread ${f.threadId}: ${f.text}`);else if("setimmediate"===f.target)a.postMessage(f);else if("callHandler"===h)w[f.handler](...f.args);else h&&E(`worker sent an unknown command ${h}`)};a.onerror=f=>{E(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],e=["print","printErr"],g;for(g of e)w.hasOwnProperty(g)&&c.push(g);a.postMessage({cmd:"load",handlers:c,
wasmMemory:k,wasmModule:Ea})});function Mb(a){A?a():Promise.all(O.map(ub)).then(a)}function tb(){var a=new Worker(new URL(import.meta.url),{type:"module",name:"em-pthread"});O.push(a)}var U=a=>{for(;0<a.length;)a.shift()(w)},Aa=()=>{var a=F(),b=v()[a+52>>2];a=v()[a+56>>2];Pb(b,b-a);yb(b)},V=[],Qb,Ca=(a,b)=>{R=0;var c=V[a];c||(a>=V.length&&(V.length=a+1),V[a]=c=Qb.get(a));a=c(b);0<R?K=a:G(a)};function Rb(a,b,c,e){return A?T(2,1,a,b,c,e):Va(a,b,c,e)}
var Va=(a,b,c,e)=>{if("undefined"==typeof SharedArrayBuffer)return E("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var g=[];if(A&&0===g.length)return Rb(a,b,c,e);a={ga:c,Y:a,fa:e,la:g};return A?(a.ea="spawnThread",postMessage(a,g),0):vb(a)},Sb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,Tb=(a,b,c)=>{var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.buffer&&Sb)return Sb.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,c):a.subarray(b,
c));for(e="";b<c;){var g=a[b++];if(g&128){var f=a[b++]&63;if(192==(g&224))e+=String.fromCharCode((g&31)<<6|f);else{var h=a[b++]&63;g=224==(g&240)?(g&15)<<12|f<<6|h:(g&7)<<18|f<<12|h<<6|a[b++]&63;65536>g?e+=String.fromCharCode(g):(g-=65536,e+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else e+=String.fromCharCode(g)}return e},C=(a,b)=>a?Tb(r(),a,b):"";function Wa(a,b,c){return A?T(3,1,a,b,c):0}function Xa(a,b,c){return A?T(4,1,a,b,c):0}function Ya(a,b,c,e){if(A)return T(5,1,a,b,c,e)}
var Za=()=>{Na("")},$a=()=>1,ab=a=>{ya(a,!z,1,!ja,2097152,!1);Ba()},za=a=>{"function"===typeof Atomics.na&&(Atomics.na(t(),a>>2,a).value.then(H),a+=128,Atomics.store(t(),a>>2,1))},H=()=>{var a=F();if(a&&(za(a),a=Ub,!Ka&&!J))try{if(a(),!(Ka||0<R))try{A?G(K):N(K)}catch(b){Eb(b)}}catch(b){Eb(b)}},bb=(a,b)=>{a==b?setTimeout(H):A?postMessage({targetThread:a,cmd:"checkMailbox"}):(a=Q[a])&&a.postMessage({cmd:"checkMailbox"})},Vb=[],cb=(a,b,c,e,g)=>{Vb.length=e;b=g>>3;for(c=0;c<e;c++)Vb[c]=ea()[b+c];return(0,Wb[a])(...Vb)},
db=a=>{A?postMessage({cmd:"cleanupThread",thread:a}):Ob(Q[a])},eb=()=>{},W=()=>{W.ca||(W.ca={});W.ca["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(W.ca["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,E("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"))},
fb=()=>{z||(W(),Na("Blocking on the main thread is not allowed by default. See https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"))},gb=()=>{R+=1;throw"unwind";},hb;hb=()=>performance.timeOrigin+performance.now();
var ib=a=>{var b=r().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);var g=Math;e=Math.max(a,e);a:{g=(g.min.call(g,2147483648,e+(65536-e%65536)%65536)-k.buffer.byteLength+65535)/65536;try{k.grow(g);n();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},Xb={},Zb=()=>{if(!Yb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||
"C").replace("-","_")+".UTF-8",_:"./this.program"},b;for(b in Xb)void 0===Xb[b]?delete a[b]:a[b]=Xb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Yb=c}return Yb},Yb;function kb(a,b){if(A)return T(6,1,a,b);var c=0;Zb().forEach((e,g)=>{var f=b+c;g=v()[a+4*g>>2]=f;for(f=0;f<e.length;++f)aa()[g++]=e.charCodeAt(f);aa()[g]=0;c+=e.length+1});return 0}function lb(a,b){if(A)return T(7,1,a,b);var c=Zb();v()[a>>2]=c.length;var e=0;c.forEach(g=>e+=g.length+1);v()[b>>2]=e;return 0}
function mb(a){return A?T(8,1,a):52}function nb(a,b,c,e){return A?T(9,1,a,b,c,e):52}function ob(a,b,c,e,g){return A?T(10,1,a,b,c,e,g):70}var Ib=[null,[],[]],Jb=(a,b)=>{var c=Ib[a];0===b||10===b?((1===a?ua:E)(Tb(c,0)),c.length=0):c.push(b)};function pb(a,b,c,e){if(A)return T(11,1,a,b,c,e);for(var g=0,f=0;f<c;f++){var h=v()[b>>2],q=v()[b+4>>2];b+=8;for(var B=0;B<q;B++)Jb(a,r()[h+B]);g+=q}v()[e>>2]=g;return 0}
var X=a=>0===a%4&&(0!==a%100||0===a%400),$b=[31,29,31,30,31,30,31,31,30,31,30,31],ac=[31,28,31,30,31,30,31,31,30,31,30,31],oa=a=>{for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);127>=e?b++:2047>=e?b+=2:55296<=e&&57343>=e?(b+=4,++c):b+=3}return b},bc=(a,b,c,e)=>{if(!(0<e))return 0;var g=c;e=c+e-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var q=a.charCodeAt(++f);h=65536+((h&1023)<<10)|q&1023}if(127>=h){if(c>=e)break;b[c++]=h}else{if(2047>=h){if(c+1>=e)break;b[c++]=
192|h>>6}else{if(65535>=h){if(c+2>=e)break;b[c++]=224|h>>12}else{if(c+3>=e)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-g};function cc(a){var b=Array(oa(a)+1);bc(a,b,0,b.length);return b}
var dc=(a,b)=>{aa().set(a,b)},ec=(a,b,c,e)=>{function g(d,m,p){for(d="number"==typeof d?d.toString():d||"";d.length<m;)d=p[0]+d;return d}function f(d,m){return g(d,m,"0")}function h(d,m){function p(Bb){return 0>Bb?-1:0<Bb?1:0}var I;0===(I=p(d.getFullYear()-m.getFullYear()))&&0===(I=p(d.getMonth()-m.getMonth()))&&(I=p(d.getDate()-m.getDate()));return I}function q(d){switch(d.getDay()){case 0:return new Date(d.getFullYear()-1,11,29);case 1:return d;case 2:return new Date(d.getFullYear(),0,3);case 3:return new Date(d.getFullYear(),
0,2);case 4:return new Date(d.getFullYear(),0,1);case 5:return new Date(d.getFullYear()-1,11,31);case 6:return new Date(d.getFullYear()-1,11,30)}}function B(d){var m=d.Z;for(d=new Date((new Date(d.$+1900,0,1)).getTime());0<m;){var p=d.getMonth(),I=(X(d.getFullYear())?$b:ac)[p];if(m>I-d.getDate())m-=I-d.getDate()+1,d.setDate(1),11>p?d.setMonth(p+1):(d.setMonth(0),d.setFullYear(d.getFullYear()+1));else{d.setDate(d.getDate()+m);break}}p=new Date(d.getFullYear()+1,0,4);m=q(new Date(d.getFullYear(),0,
4));p=q(p);return 0>=h(m,d)?0>=h(p,d)?d.getFullYear()+1:d.getFullYear():d.getFullYear()-1}var y=v()[e+40>>2];e={ja:t()[e>>2],ia:t()[e+4>>2],aa:t()[e+8>>2],da:t()[e+12>>2],ba:t()[e+16>>2],$:t()[e+20>>2],X:t()[e+24>>2],Z:t()[e+28>>2],ra:t()[e+32>>2],ha:t()[e+36>>2],ka:y?C(y):""};c=C(c);y={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var u in y)c=c.replace(new RegExp(u,"g"),y[u]);var Cb="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Db="January February March April May June July August September October November December".split(" ");y={"%a":d=>Cb[d.X].substring(0,3),"%A":d=>Cb[d.X],"%b":d=>Db[d.ba].substring(0,3),"%B":d=>Db[d.ba],"%C":d=>f((d.$+1900)/
100|0,2),"%d":d=>f(d.da,2),"%e":d=>g(d.da,2," "),"%g":d=>B(d).toString().substring(2),"%G":B,"%H":d=>f(d.aa,2),"%I":d=>{d=d.aa;0==d?d=12:12<d&&(d-=12);return f(d,2)},"%j":d=>{for(var m=0,p=0;p<=d.ba-1;m+=(X(d.$+1900)?$b:ac)[p++]);return f(d.da+m,3)},"%m":d=>f(d.ba+1,2),"%M":d=>f(d.ia,2),"%n":()=>"\n","%p":d=>0<=d.aa&&12>d.aa?"AM":"PM","%S":d=>f(d.ja,2),"%t":()=>"\t","%u":d=>d.X||7,"%U":d=>f(Math.floor((d.Z+7-d.X)/7),2),"%V":d=>{var m=Math.floor((d.Z+7-(d.X+6)%7)/7);2>=(d.X+371-d.Z-2)%7&&m++;if(m)53==
m&&(p=(d.X+371-d.Z)%7,4==p||3==p&&X(d.$)||(m=1));else{m=52;var p=(d.X+7-d.Z-1)%7;(4==p||5==p&&X(d.$%400-1))&&m++}return f(m,2)},"%w":d=>d.X,"%W":d=>f(Math.floor((d.Z+7-(d.X+6)%7)/7),2),"%y":d=>(d.$+1900).toString().substring(2),"%Y":d=>d.$+1900,"%z":d=>{d=d.ha;var m=0<=d;d=Math.abs(d)/60;return(m?"+":"-")+String("0000"+(d/60*100+d%60)).slice(-4)},"%Z":d=>d.ka,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(u in y)c.includes(u)&&(c=c.replace(new RegExp(u,"g"),y[u](e)));c=c.replace(/\0\0/g,"%");u=cc(c);
if(u.length>b)return 0;dc(u,a);return u.length-1},qb=(a,b,c,e)=>ec(a,b,c,e),pa=(a,b,c)=>bc(a,r(),b,c);A||Lb();
var Wb=[zb,Fb,Rb,Wa,Xa,Ya,kb,lb,mb,nb,ob,pb],Ua,Y=function(){function a(c,e){Y=c.exports;Kb.push(Y.G);Qb=Y.J;Ga.unshift(Y.A);Ea=e;Ma();return Y}var b=xa();L++;if(w.instantiateWasm)try{return w.instantiateWasm(b,a)}catch(c){E(`Module.instantiateWasm callback failed with error: ${c}`),x(c)}Pa||=w.locateFile?Oa("sf16-7.wasm")?"sf16-7.wasm":w.locateFile?w.locateFile("sf16-7.wasm",D):D+"sf16-7.wasm":(new URL("sf16-7.wasm",import.meta.url)).href;Ta(b,function(c){a(c.instance,c.module)}).catch(x);
return{}}();w._main=(a,b)=>(w._main=Y.B)(a,b);w.__Z10js_getlinev=a=>(w.__Z10js_getlinev=Y.C)(a);
var qa=w._uci=a=>(qa=w._uci=Y.D)(a),na=w._setNnueBuffer=(a,b,c)=>(na=w._setNnueBuffer=Y.E)(a,b,c),la=w._getRecommendedNnue=a=>(la=w._getRecommendedNnue=Y.F)(a),F=()=>(F=Y.H)(),fc=w.__emscripten_proxy_main=(a,b)=>(fc=w.__emscripten_proxy_main=Y.I)(a,b),Gb=()=>(Gb=Y.K)(),ya=(a,b,c,e,g,f)=>(ya=Y.L)(a,b,c,e,g,f),Da=()=>(Da=Y.M)(),Hb=a=>(Hb=Y.N)(a),ma=w._malloc=a=>(ma=w._malloc=Y.O)(a),xb=(a,b,c,e,g)=>(xb=Y.P)(a,b,c,e,g),Nb=a=>(Nb=Y.Q)(a),G=a=>(G=Y.R)(a),Ub=()=>(Ub=Y.S)(),Pb=(a,b)=>(Pb=Y.T)(a,b),yb=a=>
(yb=Y.U)(a),S=a=>(S=Y.V)(a),wb=()=>(wb=Y.W)();w.UTF8ToString=C;w.stringToUTF8=pa;var Z;M=function gc(){Z||hc();Z||(M=gc)};function ic(a=[]){var b=fc;R+=1;a.unshift("./this.program");var c=a.length,e=S(4*(c+1)),g=e;a.forEach(h=>{var q=v(),B=g>>2,y=oa(h)+1,u=S(y);pa(h,u,y);q[B]=u;g+=4});v()[g>>2]=0;try{var f=b(c,e);N(f,!0)}catch(h){Eb(h)}}function hc(){0<L||(A?(ha(w),A||U(Ga),startWorker(w)):(U(Fa),0<L||Z||(Z=!0,w.calledRun=!0,J||(A||U(Ga),A||U(Ha),ha(w),jc&&ic(sa),A||U(Ja)))))}var jc=!0;hc();
moduleRtn=ia;


  return moduleRtn;
}
);
})();
export default Sf167Web;
var isPthread = globalThis.self?.name === 'em-pthread';
// When running as a pthread, construct a new instance on startup
isPthread && Sf167Web();
